//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSearch.WPF {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ViewSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewSettings defaultInstance = ((ViewSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewSettings())));
        
        public static ViewSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColorThemeIndex {
            get {
                return ((int)(this["ColorThemeIndex"]));
            }
            set {
                this["ColorThemeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUploadTooltip {
            get {
                return ((bool)(this["ShowUploadTooltip"]));
            }
            set {
                this["ShowUploadTooltip"] = value;
            }
        }
    }
}
